#!/bin/bash

response=""
CURDUR=""
TMPDIR=""
updateflag="0"

# functions

## core functions

function welcomeprompt {
echo "Welcome to WLinux. Thank you for supporting sustainable indepdendent open source development."
echo
echo "WLinux comes with a core set of packages. This script allows you to install additional sets of curated packages."
echo
}

function continueprompt {
read -r -p "Would you like to continue with this setup script? [Y/n] " response
if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]
then
    echo "Continuing with setup."
else
    echo "You may run the script again any time by running: bash /etc/setup"
    exit 0
fi
}

function updatescriptprompt {
read -r -p "Would you like to download and run an updated version of this setup from GitHub? [y/N] " response
if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]
then
    TMPDIR=$(mktemp -d)
    curl https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/oobe-staging/linux_files/setup | bash -s u
    exit 0
else
    echo "Continuing with release install script."
fi
}

function securitypatches {
echo "Checking for security updates."
}

## internationalization

function languageprompt {
read -r -p "Would you like to configure additional languages? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    sudo dpkg-reconfigure locales
fi
}

## package meta functions

    # list all package sets and the order they should be presented for optional install here

function installpackages {
echo "[Editors]"
neoviminstall
emacsinstall
echo "[Enhancements]"
fzfinstall
azurecliinstall
echo "[Development Environment]"
pythoninstall
echo "[GUI Applications]"
basicguiinstall
codeinstall
chromeinstall
hidpiconfig
}

function updateupgrade {
sudo apt update
sudo apt upgrade -y
}

function shellmenu () {
    echo "Shells:"
    for i in ${!options[@]}; do 
        printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${options[i]}"
    done
    [[ "$msg" ]] && echo "$msg"; :
}

# This is a testing function, so I didn't include it other codes.
function installandsetshell {
options=("zsh" "fish" "csh")

prompt="Check a shell (again to uncheck, ENTER when done): "
while shellmenu && read -rp "$prompt" num && [[ "$num" ]]; do
    [[ "$num" != *[![:digit:]]* ]] &&
    (( num > 0 && num <= ${#options[@]} )) ||
    { msg="Invalid option: $num"; continue; }
    ((num--)); msg="${options[num]} was ${choices[num]:+un}checked"
    [[ "${choices[num]}" ]] && choices[num]="" || choices[num]="+"
done

toselect=("bash")
msg="1"
for i in ${!options[@]}; do 
    if [[ "${choices[i]}" ]]
    then
        toselect+=("${options[i]}")
        echo "Installing ${options[i]}..."
        sudo apt install ${options[i]} -y
        msg="0"
    fi
done
if [[ "$msg" == "1" ]]
then
    echo "No extra shell is selected, continuing setup..."
else
    echo "Set default shell:"
    for i in ${!toselect[@]}; do 
        printf "%3d) %s\n" $((i)) "${toselect[i]}"
    done
    passed="1"
    while [[ "$passed" == "1" ]]
    do
        read -rp "Type a number and enter: " opt
        if [[ "$opt" != *[![:digit:]]* ]] && (( opt < 0 && opt >= ${#toselect[@]} ))
        then
            echo "Invalid option: $opt"
        elif [[ "$opt" == "" ]]
        then
            echo "Value should not be empty"
        else
            passed="0"
        fi
    done
    echo "Setting ${toselect[$opt]} as default..."
    chsh -s $(which ${toselect[$opt]})
fi
}

## package set functions

### editors

function neoviminstall {
read -r -p "Would you like to download and install optional editor neovim? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    sudo apt install neovim -y
fi
}

function emacsinstall {
read -r -p "Would you like to download and install optional editor emacs? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    sudo apt install emacs -y
fi
}

function codeinstall {
read -r -p "Would you like to download and install optional editor Microsoft Code? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    CURDIR=$(pwd)
    TMPDIR=$(mktemp -d)
    cd $TMPDIR
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg 
    sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg 
    sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list' 
    sudo apt upgrade -y 
    sudo apt update
    sudo apt install code libxss1 libasound2 -y
    cd $CURDIR
    rm -r $TMPDIR
fi  
}

### gui apps

function basicguiinstall {
read -r -p "Would you like to download and install a base set of libraries for GUI packages? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    sudo apt install xclip gnome-themes-standard gtk2-engines-murrine dbus-x11 -y
fi    
}

function chromeinstall {
read -r -p "Would you like to download and install Google Chrome? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    CURDIR=$(pwd)
    TMPDIR=$(mktemp -d)
    cd $TMPDIR
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
    sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main " > /etc/apt/sources.list.d/googlechrome.list' 
    sudo apt update
    sudo apt upgrade -y
    sudo apt install google-chrome-stable -y
    cd $CURDIR
    rm -r $TMPDIR
fi    
}

function hidpiconfig {
read -r -p "Would you like to configure Qt and GDK for HiDPI displays (set scaling factor to 2)? [y/N] " response
if [[ $response == ^[yY]$ ]]
    export QT_SCALE_FACTOR=2
    export GDK_SCALE=2
    sudo echo 'export QT_SCALE_FACTOR=2' >> /etc/profile
    sudo echo 'export GDK_SCALE=2' >> /etc/profile
fi    
}

### dev environments

function pythoninstall {
read -r -p "Would you like to download and install python 3.7, IDLE, and pip package manager? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    CURDIR=$(pwd)
    TMPDIR=$(mktemp -d)
    cd $TMPDIR
    apt update
    sudo apt -t testing install build-essential python3.7 idle-python3.7 -y
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python3 get-pip.py --user
    export PATH="$PATH:/home/~/.local/bin"
    echo 'export PATH="$PATH:/home/~/.local/bin"' >> ~/.bashrc
    pip install -U pip
    cd $CURDIR
    rm -r $TMPDIR
fi   
}

### enhancements

function fzfinstall {
read -r -p "Would you like to download and install optional command line finder fzf? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    CURDIR=$(pwd)
    TMPDIR=$(mktemp -d)
    cd $TMPDIR
    git clone --depth 1 https://github.com/junegunn/fzf.git
    cd fzf
    ./install
    cd $CURDIR
    rm -r $TMPDIR
fi   
}

### cloud tools

function azurecliinstall {
read -r -p "Would you like to download and install optional Azure cloud command line tools? [y/N] " response
if [[ $response == ^[yY]$ ]]
then
    CURDIR=$(pwd)
    TMPDIR=$(mkdir -d)
    cd $TMPDIR
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    sudo cp microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
    sudo chmod 644 /etc/apt/trusted.gpg.d/microsoft.gpg
    sudo bash -c "echo 'deb https://packages.microsoft.com/repos/azure-cli/ stretch main' >> /etc/apt/sources.list.d/azurecli.list"
    sudo apt update 
    sudo apt upgrade -y
    echo "Note: azure-cli install can appear to 'stall' at 16%, it is usually not broken, just taking a long time."
    sudo apt install azure-cli -y
    cd $CURDIR
    rm -r $TMPDIR
fi
}

# main

## process update command line flag to detect if running from update script
while [ $1 ]; do
	case $1 in
		-u) $updateflag="0";shift;;
	esac
done

## setup script

if [[ "$updateflag" == "1" ]]
then
  echo "Continuing with updated script from GitHub."
  updateupgrade
  securitypatches
  installpackages
else
  welcomeprompt
  continueprompt
  languageprompt
  updatescriptprompt
  updateupgrade
  installandsetshell
  securitypatches
  installpackages
fi

exit 0